apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry
commonLabels:
  app: opentelemetry
  component: otel-agent
configMapGenerator:
- name: otel-agent-conf
  files:
  - otel-agent-config.yaml
resources:
- daemonset.yaml
