apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-demo
spec:
  template:
    spec:
      containers:
      - name: tracing-demo
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: otel-agent.opentelemetry:55680
