apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-state-metrics
commonLabels:
  app: kube-state-metrics
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
- serviceaccount.yaml