apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  annotations:
    # note that this isn't the recommended approach: 
    # https://github.com/kubernetes/kube-state-metrics/pull/957
    prometheus.io/scrape: "true"
    # only scrape the state metrics, not debugging ones
    prometheus.io/port: "8080"
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  # - name: telemetry
  #   port: 8081
  #   targetPort: telemetry
