apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otel-collector
spec:
  template:
    metadata:
      annotations:
        prometheus.io/collector: "true"
        prometheus.io/internalport: "8888"
        prometheus.io/externalport: "8889"
    spec:
        serviceAccountName: collector
