scrape_configs:
- job_name: 'metric-relabel-config'
  scrape_interval: 10s
  static_configs:
  - targets: ['0.0.0.0:9090']
  metric_relabel_configs:
  - source_labels: [__address__]
    replacement: instance_replacement
    target_label: instance