bases:
- ../../base
namespace: opentelemetry
configMapGenerator:
- name: otel-collector-conf
  behavior: merge
  files:
  - otel-collector-config.yaml
patches:
- statefulset.yaml
- service.yaml
resources:
- rbac.yaml