apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
    app.kubernetes.io/name: rabbitmq
resources:
- rabbitmqcluster.yaml
- configmap.yaml
- monitoringdashboard.yaml