apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry
commonLabels:
  app: opentelemetry
resources:
- agent-conf.yaml
- agent-daemonset.yaml
- collector-conf.yaml
- collector-deployment.yaml
- collector-service.yaml
- namespace.yaml
