apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
commonLabels:
  app: prometheus
  component: core
configMapGenerator:
- name: prometheus-config
  files:
  - prometheus-config.yaml
resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml
- service.yaml