scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector.opentelemetry.svc:8889']
      - targets: ['otel-collector.opentelemetry.svc:8888']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']