apiVersion: v1
data:
  workload-metrics-config: |
    receivers:
        prometheus:
            config:
                scrape_configs:
                    - job_name: default/rabbitmq/0
                      relabel_configs:
                        - source_labels: [__meta_kubernetes_pod_container_port_name]
                          action: keep
                          regex: metrics
                        - source_labels: [__meta_kubernetes_namespace]
                          action: replace
                          target_label: gke_kubernetes_namespace
                        - source_labels: [__meta_kubernetes_pod_name]
                          action: replace
                          target_label: gke_kubernetes_pod_name
                        - source_labels: [__meta_kubernetes_pod_container_name]
                          action: replace
                          target_label: gke_kubernetes_container_name
                        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                          action: keep
                          regex: rabbitmq
                        - source_labels: [__meta_kubernetes_namespace]
                          action: keep
                          regex: default
                      metric_relabel_configs:
                        - source_labels: [__name__]
                          action: keep
                          regex: rabbitmq_.*
                        - source_labels: [__name__]
                          action: drop
                          regex: rabbitmq_queue_.*
                      metrics_path: /metrics
                      kubernetes_sd_configs:
                        - role: pod
                          selectors:
                            - role: pod
                              field: spec.nodeName=$NODE_NAME
                    - job_name: default/rabbitmq/1
                      relabel_configs:
                        - source_labels: [__meta_kubernetes_pod_container_port_name]
                          action: keep
                          regex: metrics
                        - source_labels: [__meta_kubernetes_namespace]
                          action: replace
                          target_label: gke_kubernetes_namespace
                        - source_labels: [__meta_kubernetes_pod_name]
                          action: replace
                          target_label: gke_kubernetes_pod_name
                        - source_labels: [__meta_kubernetes_pod_container_name]
                          action: replace
                          target_label: gke_kubernetes_container_name
                        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                          action: keep
                          regex: rabbitmq
                        - source_labels: [__meta_kubernetes_namespace]
                          action: keep
                          regex: default
                      metric_relabel_configs:
                        - source_labels: [__name__]
                          action: keep
                          regex: rabbitmq_queue_.*
                      metrics_path: /metrics/per-object
                      kubernetes_sd_configs:
                        - role: pod
                          selectors:
                            - role: pod
                              field: spec.nodeName=$NODE_NAME
    exporters:
      logging:
        logLevel: debug
    service:
        pipelines:
            metrics:
                receivers:
                    - prometheus
                processors:
                    - memory_limiter/container
                    - resource/container
                    - metric_to_resource/container
                exporters:
                    - googlecloud
                    - logging
kind: ConfigMap
metadata:
  name: rabbitmq
  labels:
    monitoring.gke.io/collector-patch: "true"
  namespace: default
