apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: podmonitor-loadtest
spec:
  selector:
    matchLabels:
      app: load-testing
  namespaceSelector:
    matchNames:
    - load-testing
  podMetricsEndpoints:
  - port: metrics