apiVersion: apps/v1
kind: Deployment
metadata:
        name: guaranteed-deployment
spec:
        replicas: 5
        template:
                metadata:
                        labels:
                                app: guaranteed
                spec:
                        containers:
                        - name: guaranteed
                          image: busybox
                          args: ["sh", "-c", "while true; do sleep 10; done"]
                          resources:
                                  requests:
                                          cpu: "10m"
                                          memory: "1000Mi"
                                  limits:
                                          cpu: "10m"
                                          memory: "1000Mi"

