apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gke-workload-metrics
commonLabels:
  app: prom-example
resources:
- deployment.yaml
- namespace.yaml
- podmonitor.yaml
  #- poddashboard.yaml
