apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-exporter
commonLabels:
    app.kubernetes.io/name: node-exporter
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- daemonset.yaml
- namespace.yaml
- serviceaccount.yaml