apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  template:
    spec:
      containers:
      - image: openzipkin/zipkin
        name: zipkin
        ports:
        - containerPort: 9411
          name: http
