apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaeger
commonLabels:
  app: jaeger
  component: all-in-one
resources:
- collector-service.yaml
- deployment.yaml
- namespace.yaml
- query-service.yaml