apiVersion: batch/v1
kind: Job
metadata:
  name: tracing-demo
spec:
  template:
    spec:
      containers:
      - image: gcr.io/dashpole-gke-dev/tracing_demo:v0.0.1
        name: tracing-demo
      restartPolicy: "OnFailure"
