bases:
- ../../base
namespace: opentelemetry
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: otel-collector-conf
  behavior: merge
  files:
  - otel-collector-config.yaml
patches:
- service.yaml