apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
spec:
  template:
    spec:
      containers:
      - name: otel-agent
        ports:
        - containerPort: 55680 # Default OpenTelemetry receiver port.
          hostPort: 55680